-- Drop existing tables if they exist (for test resets)
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;

-- PRODUCTS table
CREATE TABLE IF NOT EXISTS products
(
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    price DECIMAL(10, 2) NOT NULL,
    stock_quantity INT NOT NULL,
    category VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
    );

-- ORDERS table
CREATE TABLE IF NOT EXISTS orders
(
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    payment_status VARCHAR(255),
    status VARCHAR(255),
    total_amount DOUBLE PRECISION,
    CONSTRAINT orders_payment_status_check
    CHECK (payment_status IN ('PENDING','SUCCESS','FAILED')),
    CONSTRAINT orders_status_check
    CHECK (status IN ('PENDING','PAID','READY','COMPLETED','CANCELLED'))
    );

-- ORDER_ITEMS table
CREATE TABLE IF NOT EXISTS order_items
(
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price DOUBLE PRECISION NOT NULL,
    quantity INT NOT NULL,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT fk_order FOREIGN KEY (order_id)
    REFERENCES orders (order_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    CONSTRAINT fk_product FOREIGN KEY (product_id)
    REFERENCES products (product_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    );
