CREATE TABLE IF NOT EXISTS products (product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,category VARCHAR(255),
    created_at TIMESTAMP,
    description VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    price DOUBLE NOT NULL,
    stock_quantity INT NOT NULL,
    updated_at TIMESTAMP
    );
